class Location:
  BOAT = 65
  LIGHTHOUSE = 85
  WATERFALL = 135
  CAMPING_LAKE = 65
  IGLOO = 170
  UNDERGROUND_SEWER = 65
  RESORT_POOL = 65
  RESORT_BEACH = 85
  MALL = 65
  FISHING_SPOT = 65
  DOWNTOWN_FOUNTAIN = 65
  DOWNTOWN_POND = 65
  BLUE_HOLE = 65


class Config:
  MARK_POSITION_X = 100
  MARK_POSITION_Y = 520
  MARK_POSITION_Y = Location.BOAT
  MARK_WIDTH = 200
  MARK_HEIGHT = 40
  MARK_SQUARE = MARK_WIDTH * MARK_HEIGHT
  STD_EPSILON = 10000000
  STD_CHANGE_THRESHOLD = 1
  DEBUG = False
  HAS_MEMBERSHIP = True
  SELL_ALL_FISH = False
