class Location:
  BOAT = 65
  LIGHTHOUSE = 85
  WATERFALL = 150
  CAMPING_LAKE = 65
  IGLOO = 140
  UNDERGROUND_SEWER = 125
  HOME_RESORT_POOL = 65
  HOME_RESORT_BEACH = 85
  MALL = 155
  FISHING_SPOT = 65
  DOWNTOWN_FOUNTAIN = 150
  DOWNTOWN_POND = 125
  BLUE_HOLE = 165
  STADIUM_DEEP_SEA = 150
  RESORT_DEEP_SEA = 105
  RESORT_NORTH_ISLAND_POND = 85
  PLAZA_BEACH = 20


class Config:
  MARK_POSITION_X = 100
  MARK_POSITION_Y = 520
  MARK_POSITION_Y = Location.BOAT
  MARK_WIDTH = 200
  MARK_HEIGHT = 40
  MARK_SQUARE = MARK_WIDTH * MARK_HEIGHT
  STD_EPSILON = 10000000
  STD_CHANGE_THRESHOLD = 1
  DEBUG = False
  HAS_MEMBERSHIP = True
  SELL_ALL_FISH = False
  SAVE_FISH_IMAGE = False
  FISH_IMAGE_DIR = 'data'
