class Config:
  MARK_POSITION_X = 100
  MARK_POSITION_Y = 520
  MARK_WIDTH = 200
  MARK_HEIGHT = 40
  MARK_SQUARE = MARK_WIDTH * MARK_HEIGHT
  STD_EPSILON = 10000000
  STD_CHANGE_THRESHOLD = 5
  DEBUG = False
  HAS_MEMBERSHIP = False
  SELL_ALL_FISH = False
